displayName: ResponseTimeBalancer
type: middleware
iconPath: .assets/icon.png

import: github.com/ArtemUgrimov/ResponseTimeBalancer

summary: 'Resetting cookie if the value defined in some header exceeds specified amount'

testData:
  rtb_static:
    responseTimeHeaderName: "Tm"
    responseTimeLimitMs: "80"
    cookieSetHeaderValue: "invalidated"

    logStartup: true
    logSetCookie: true
    logLimitNotReached: true
    logHeaderNotFound: true
