displayName: ResponseTimeBalancer
type: middleware
iconPath: .assets/icon.png

import: github.com/ArtemUgrimov/ResponseTimeBalancer

summary: 'Removing cookie if response time exceeds specified amount ms'

testData:
  rtb_static:
    cookiePodIdName: "pod-id"
    additionalCookie: "; Path=/"
    responseTimeHeaderName: "Tm"
    responseTimeDiffMsToInvalidate: "30"
    logStart: true
    logCookieFound: false
    logCookieResetToBest: true
    logIdle: false
    logBestUpdate: true
