displayName: ResponseTimeBalancer
type: middleware
iconPath: .assets/icon.png

import: github.com/ArtemUgrimov/ResponseTimeBalancer

summary: 'Removing cookie if response time exceeds specified amount ms'

testData:
  cookie_name: "pod-id"
  response_time_limit_ms: 50
