displayName: ResponseTimeBalancer
type: middleware
iconPath: .assets/icon.png

import: github.com/ArtemUgrimov/ResponseTimeBalancer

summary: 'Load balancer by header value'

testData:
  rtb_static:
    namespace: "rc"
    serviceName: "bng-server"
    updateInterval: "10s"
